# Golang CircleCI 2.0 configuration file

version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/tripleaceinnovations/api/
    
    parallelism: 2

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
      
    steps:
      - checkout
      - run: pwd
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - run: pwd
      #- run: 
          #name: Get Dependency
          #command: go get github.com/jstemmer/go-junit-report
      - run: ls -latr
      # specify any bash command here prefixed with `run: `
      #- run: go get -v -t -d ./...
      - run: 
          name: Run unit tests
          command: |
            cd models
            go test -v
            #trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            # make test | tee ${TEST_RESULTS}/go-test.out
